config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/pages' => 'pages#index'
  get '/pages/new' => 'pages#new'
  post '/pages' => 'pages#create'
  get '/pages/:id' => 'pages#show', as: 'page'
  get '/pages/:id/edit' => 'pages#edit', as: 'page_edit'
  patch '/pages/:id' => 'pages#update'

end

app/models/page.rb
class Page < ActiveRecord::Base
	serialize :modules, Array

	validates :title, presence: true

	has_many :text_blocks
	accepts_nested_attributes_for :text_blocks, :allow_destroy => true
end

app/models/text_block.rb
class TextBlock < ActiveRecord::Base
  belongs_to :page
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@pages = Page.all
	end

	def show
		@page = Page.find(params[:id])
	end

	def new
		@page = Page.new
	end

	def create
		@page = Page.new(page_params)

    i = 0
    until i = 3
      @text_block = @page.text_blocks.new(page_params[:text_blocks_attributes]["#{i}"])
      @text_block.save
      i += 1
    end

		if @page.save
			redirect_to pages_url
		else
			render :new
		end
	end

	def edit
		@page = Page.find(params[:id])
	end

	def update
		@page = Page.find(params[:id])

    i = 0
    until i = 3
      @text_block = @page.text_blocks["#{i}"]
      @text_block.update_attributes(page_params[:text_blocks_attributes]["#{i}"])
      i += 1
    end

		if @page.update_attributes(page_params)
			redirect_to pages_url
		else
			render :edit
		end
	end

	private

	  def page_params
	  	params.require(:page).permit(:title, :modules => [], :text_blocks_attributes => [:id, :header, :content, :_destroy])
	  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_new_module(text, form_obj, _module)
		text_block_object = form_obj.object.send(:text_blocks).klass.new
		text_block_id = text_block_object.object_id

		select = '<div class="row"><div class="form-group col-md-10">'
		select += render('modules_select', :i => _module, :p => form_obj)
		select += '</div><div class="form-group col-md-2">'
		select += link_to 'Remove', '#', class: 'btn btn-primary remove-module'
		select +=	'</div></div>'
		text_block = '<div class="well">'
		text_block += form_obj.fields_for(:text_blocks, text_block_object, child_index: text_block_id) do |builder|
			render('text_block_options', :field => builder)
		end
		# text_block += render('modules_select'
		text_block += '</div>'
		link_to text, '#', data: {select: select.gsub(/\n/, ''), text_block: text_block.gsub(/\n/, '')}, class: 'add-module'
	end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PageCreator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page do |p| %>

  <div class="form-group">
  	<%= p.label :title %>
  	<%= p.text_field :title, class: 'form-control' %>
  </div>

	<% if @page.new_record? %>

	  <div class="row">
		  <div class="form-group col-md-10">
		  	<%= render 'modules_select', :i => 0, :p => p %>
			</div>

			<div class="form-group col-md-2">
				<%= link_to 'Remove', '#', class: 'btn btn-primary remove-module' %>
			</div>
		</div>

		<div class="well">
			<%= p.fields_for :text_blocks, @page.text_blocks.build do |t| %> 
				<%= render 'text_block_options', :field => t %>
			<% end %>
		</div>

	<% else %>

	  <% for i in 0..@page.modules.length-1 %>

		  <div class="row">
			  <div class="form-group col-md-10">
				  <%= render 'modules_select', :i => i, :p => p %>
				</div>

				<div class="form-group col-md-2">
					<%= link_to 'Remove', '#', class: 'btn btn-primary remove-module' %>
				</div>
			</div>

			<div class="well">
				<%= p.fields_for :text_blocks, @page.text_blocks[i] do |t| %> 
					<%= render 'text_block_options', :field => t %>
				<% end %>
			</div>

	  <% end %>

  <% end %>

  <div class="form-group">
  	<%= link_to_new_module 'Add Section', p, i %>
	</div>

  <div class="form-group">
  	<%= p.submit class: "btn btn-primary" %>
	</div>

<% end %>

app/views/pages/_modules_select.html.erb
<%= select_tag( :modules[i.to_i], options_for_select([['Text Block', 'text_block'],['Waluigi Time', 'waaaaaaaa']], p.object.modules[0]), {class: 'form-control', name: 'page[modules][]'} ) %>

app/views/pages/_text_block.html.erb
<h2><%= text_block.header %></h2>

<p><%= text_block.content %></p>

app/views/pages/_text_block_options.html.erb
<div class="form-group">
	<%= field.label :header %>
	<%= field.text_field :header, class: 'form-control' %>
</div>

<div class="form-group">
	<%= field.label :content %>
	<%= field.text_area :content, class: 'form-control' %>
</div>

<%= field.hidden_field :_destroy, class: 'destroy-field' %>

app/views/pages/edit.html.erb
<div class="container">

	<h1>Edit Page</h1>

	<%= render 'form' %>


	<ul class="list-group">
		<li class="list-group-item">
			<%= link_to 'back', page_path(params[:id]) %>
		</li>
	</ul>

</div>

app/views/pages/index.html.erb
<div class="container">
	<h1 class="page-header">Pages</h1>
	<div class="row">
 
		<% @pages.each do |page| %>
			<div class="col-md-4">

				<h2><%= link_to page.title, page_path(page.id) %></h2>

				<h4>Contains these items:</h4>
				<ul>

					<% page.modules.each do |m| %>
					  <li><%= m %></li>
					<% end %>

				</ul>

			</div>
		<% end %>

	</div>

	<ul class="list-group">
		<li class="list-group-item">
			<%= link_to 'New Page', pages_new_path %>
		</li>
	</ul>
</div>

app/views/pages/new.html.erb
<div class="container">

	<h1>New Page</h1>

	<%= render 'form' %>

	<ul class="list-group">
		<li class="list-group-item">
			<%= link_to 'Pages', pages_path %>
		</li>
	</ul>

</div>

app/views/pages/show.html.erb
<div class="container">

	<h1><%= @page.title %></h1>

	<% @text_block_count = 0 %>
	<% @page.modules.each do |m| %>
		<div class="container module">
			<div class="row">
				<% case m 
					 when 'text_block' %>

					<%= render 'text_block', text_block: @page.text_blocks[@text_block_count] %>
					<% @text_block_count += 1 %>

				<% when 'waaaaaaaa' %>
					<%= image_tag("waluigi_time.jpg", :alt => "Waaaaaaaa!!!") %>
				<% end %>
			</div>
		</div>
	<% end %>

	<ul class="list-group">
		<li class="list-group-item">
			<%= link_to 'pages', pages_path %>
		</li>
		<li class="list-group-item">
			<%= link_to 'edit page', page_edit_path(@page.id) %>
		</li>
	</ul>

</div>

app/views/static_pages/home.html.erb
Hello world!